// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PrimaryRayModule.proto

#ifndef PROTOBUF_PrimaryRayModule_2eproto__INCLUDED
#define PROTOBUF_PrimaryRayModule_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ElVis {
namespace Serialization {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_PrimaryRayModule_2eproto();
void protobuf_AssignDesc_PrimaryRayModule_2eproto();
void protobuf_ShutdownFile_PrimaryRayModule_2eproto();

class PrimaryRayModule;

// ===================================================================

class PrimaryRayModule : public ::google::protobuf::Message {
 public:
  PrimaryRayModule();
  virtual ~PrimaryRayModule();

  PrimaryRayModule(const PrimaryRayModule& from);

  inline PrimaryRayModule& operator=(const PrimaryRayModule& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PrimaryRayModule& default_instance();

  void Swap(PrimaryRayModule* other);

  // implements Message ----------------------------------------------

  inline PrimaryRayModule* New() const { return New(NULL); }

  PrimaryRayModule* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrimaryRayModule& from);
  void MergeFrom(const PrimaryRayModule& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrimaryRayModule* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ElVis.Serialization.PrimaryRayModule)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_PrimaryRayModule_2eproto();
  friend void protobuf_AssignDesc_PrimaryRayModule_2eproto();
  friend void protobuf_ShutdownFile_PrimaryRayModule_2eproto();

  void InitAsDefaultInstance();
  static PrimaryRayModule* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PrimaryRayModule

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Serialization
}  // namespace ElVis

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PrimaryRayModule_2eproto__INCLUDED
