// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VolumeRenderingModule.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "VolumeRenderingModule.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ElVis {
namespace Serialization {

namespace {

const ::google::protobuf::Descriptor* VolumeRenderingModule_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  VolumeRenderingModule_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_VolumeRenderingModule_2eproto() {
  protobuf_AddDesc_VolumeRenderingModule_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "VolumeRenderingModule.proto");
  GOOGLE_CHECK(file != NULL);
  VolumeRenderingModule_descriptor_ = file->message_type(0);
  static const int VolumeRenderingModule_offsets_[1] = {
  };
  VolumeRenderingModule_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      VolumeRenderingModule_descriptor_,
      VolumeRenderingModule::default_instance_,
      VolumeRenderingModule_offsets_,
      -1,
      -1,
      -1,
      sizeof(VolumeRenderingModule),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VolumeRenderingModule, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(VolumeRenderingModule, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_VolumeRenderingModule_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      VolumeRenderingModule_descriptor_, &VolumeRenderingModule::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_VolumeRenderingModule_2eproto() {
  delete VolumeRenderingModule::default_instance_;
  delete VolumeRenderingModule_reflection_;
}

void protobuf_AddDesc_VolumeRenderingModule_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033VolumeRenderingModule.proto\022\023ElVis.Ser"
    "ialization\"\027\n\025VolumeRenderingModuleb\006pro"
    "to3", 83);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "VolumeRenderingModule.proto", &protobuf_RegisterTypes);
  VolumeRenderingModule::default_instance_ = new VolumeRenderingModule();
  VolumeRenderingModule::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_VolumeRenderingModule_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_VolumeRenderingModule_2eproto {
  StaticDescriptorInitializer_VolumeRenderingModule_2eproto() {
    protobuf_AddDesc_VolumeRenderingModule_2eproto();
  }
} static_descriptor_initializer_VolumeRenderingModule_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

VolumeRenderingModule::VolumeRenderingModule()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ElVis.Serialization.VolumeRenderingModule)
}

void VolumeRenderingModule::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

VolumeRenderingModule::VolumeRenderingModule(const VolumeRenderingModule& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ElVis.Serialization.VolumeRenderingModule)
}

void VolumeRenderingModule::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

VolumeRenderingModule::~VolumeRenderingModule() {
  // @@protoc_insertion_point(destructor:ElVis.Serialization.VolumeRenderingModule)
  SharedDtor();
}

void VolumeRenderingModule::SharedDtor() {
  if (this != default_instance_) {
  }
}

void VolumeRenderingModule::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VolumeRenderingModule::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return VolumeRenderingModule_descriptor_;
}

const VolumeRenderingModule& VolumeRenderingModule::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_VolumeRenderingModule_2eproto();
  return *default_instance_;
}

VolumeRenderingModule* VolumeRenderingModule::default_instance_ = NULL;

VolumeRenderingModule* VolumeRenderingModule::New(::google::protobuf::Arena* arena) const {
  VolumeRenderingModule* n = new VolumeRenderingModule;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VolumeRenderingModule::Clear() {
}

bool VolumeRenderingModule::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ElVis.Serialization.VolumeRenderingModule)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:ElVis.Serialization.VolumeRenderingModule)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ElVis.Serialization.VolumeRenderingModule)
  return false;
#undef DO_
}

void VolumeRenderingModule::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ElVis.Serialization.VolumeRenderingModule)
  // @@protoc_insertion_point(serialize_end:ElVis.Serialization.VolumeRenderingModule)
}

::google::protobuf::uint8* VolumeRenderingModule::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ElVis.Serialization.VolumeRenderingModule)
  // @@protoc_insertion_point(serialize_to_array_end:ElVis.Serialization.VolumeRenderingModule)
  return target;
}

int VolumeRenderingModule::ByteSize() const {
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void VolumeRenderingModule::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const VolumeRenderingModule* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const VolumeRenderingModule>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void VolumeRenderingModule::MergeFrom(const VolumeRenderingModule& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
}

void VolumeRenderingModule::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VolumeRenderingModule::CopyFrom(const VolumeRenderingModule& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VolumeRenderingModule::IsInitialized() const {

  return true;
}

void VolumeRenderingModule::Swap(VolumeRenderingModule* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VolumeRenderingModule::InternalSwap(VolumeRenderingModule* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata VolumeRenderingModule::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = VolumeRenderingModule_descriptor_;
  metadata.reflection = VolumeRenderingModule_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// VolumeRenderingModule

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Serialization
}  // namespace ElVis

// @@protoc_insertion_point(global_scope)
