# - Try to find ProjectX
# Once done this will define
#  
#  PROJECTX_FOUND        - system has PROJECTX
#  PROJECTX_INCLUDE_DIR  - the PROJECTX include directory
#  PROJECTX_LIBRARY_DIR  - where the libraries are
#  PROJECTX_LIBRARY      - Link these to use PROJECTX
#   

SET(PROJECTX_DIR $ENV{PX_DIR} CACHE PATH "ProjectX Source Directory")
SET(PROJECTX_ARC $ENV{PX_ARC} CACHE PATH "ProjectX Build")

SET(PX_BUILD_DIR ${PROJECTX_DIR}/platforms/${PROJECTX_ARC} )

IF( UNIX )
  # header files
  FIND_PATH( PROJECTX_INCLUDE_DIR PXSolver.h 
             PATHS ${PROJECTX_DIR}/include )

  FIND_LIBRARY( PROJECTX_LIBRARY_FUNDAMENTALS
                 NAMES PXFundamentals
                 PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_REFERENCE
                 NAMES PXReference
                 PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_GRID
                 NAMES PXGrid
                 PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_CUTCELL3D
                 NAMES PXCutCell3d
                 PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_COMPRESSIBLE
                 NAMES PXCompressible
                 PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_PX
                 NAMES PX
                 PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_LINEARSOLVER
                NAMES PXLinearSolver
                PATHS ${PX_BUILD_DIR}/lib )

  FIND_LIBRARY( PROJECTX_LIBRARY_ADAPT
                NAMES PXAdaptMechanics
                PATHS ${PX_BUILD_DIR}/lib )

#  FIND_LIBRARY( CGNS_LIBRARY
#                 NAMES cgns
#                 PATHS ${PX_BUILD_DIR}/lib )


  FIND_LIBRARY( UMFPACK_LIBRARY 
                NAMES umfpack
                PATHS $ENV{UMFAMD_DIR}/umfpack/UMFPACK/Lib )

  FIND_LIBRARY( CHOLMOD_LIBRARY 
                NAMES cholmod )

  FIND_LIBRARY( SUITESPARSE_LIBRARY 
                NAMES suitesparseconfig )

  FIND_LIBRARY( AMD_LIBRARY 
                NAMES amd
                PATHS $ENV{UMFAMD_DIR}/umfpack/AMD/lib )

  FIND_LIBRARY( COLAMD_LIBRARY 
                NAMES colamd )

  FIND_LIBRARY( NLOPT_LIBRARIES nlopt
                PATHS $ENV{NLOPT_DIR}/lib )

  IF( NOT NLOPT_LIBRARIES )
    UNSET( NLOPT_LIBRARIES CACHE )
  ENDIF()

  SET(PROJECTX_LIBRARIES ${PROJECTX_LIBRARY_FUNDAMENTALS} ${PROJECTX_LIBRARY_REFERENCE} ${PROJECTX_LIBRARY_GRID} ${PROJECTX_LIBRARY_CUTCELL3D} ${PROJECTX_LIBRARY_COMPRESSIBLE} ${PROJECTX_LIBRARY_PX} ${PROJECTX_LIBRARY_LINEARSOLVER} ${PROJECTX_LIBRARY_ADAPT} ${CGNS_LIBRARY} ${UMFPACK_LIBRARY} ${AMD_LIBRARY} ${CHOLMOD_LIBRARY} ${COLAMD_LIBRARY} ${SUITESPARSE_LIBRARY} ${NLOPT_LIBRARIES} ${PROJECTX_LIBRARY_FUNDAMENTALS})


IF (PROJECTX_INCLUDE_DIR AND PROJECTX_LIBRARIES)
   SET(PROJECTX_FOUND TRUE)
    SET( PROJECTX_LIBRARY_DIR ${PX_BUILD_DIR}/lib )
ELSE (PROJECTX_INCLUDE_DIR AND PROJECTX_LIBRARIES)
   SET( PROJECTX_FOUND FALSE )
   SET( PROJECTX_LIBRARY_DIR )
ENDIF (PROJECTX_INCLUDE_DIR AND PROJECTX_LIBRARIES)

endif( UNIX )


